// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8rjE91K93X1j_GQgwwxbT8n7AlAEM7uM',
    appId: '1:857113504270:web:f1dd3c712aa997a424ea5f',
    messagingSenderId: '857113504270',
    projectId: 'erik-93b5c',
    authDomain: 'erik-93b5c.firebaseapp.com',
    storageBucket: 'erik-93b5c.appspot.com',
    measurementId: 'G-JGFP8KS8Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCga-euCKiuMDtQwhKc9xlIY_BsAIu2uB4',
    appId: '1:857113504270:android:897cae25316588b224ea5f',
    messagingSenderId: '857113504270',
    projectId: 'erik-93b5c',
    storageBucket: 'erik-93b5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZKhEpyjGVDhwHOWNW2GvnHGNv0vDW8DU',
    appId: '1:857113504270:ios:cdde1b207238e41424ea5f',
    messagingSenderId: '857113504270',
    projectId: 'erik-93b5c',
    storageBucket: 'erik-93b5c.appspot.com',
    iosClientId: '857113504270-5ra27q7b4kdebilgbb9mpt16oitvq9iu.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.erik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZKhEpyjGVDhwHOWNW2GvnHGNv0vDW8DU',
    appId: '1:857113504270:ios:cdde1b207238e41424ea5f',
    messagingSenderId: '857113504270',
    projectId: 'erik-93b5c',
    storageBucket: 'erik-93b5c.appspot.com',
    iosClientId: '857113504270-5ra27q7b4kdebilgbb9mpt16oitvq9iu.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.erik',
  );
}
